graph TB
    User[User] --> Post[Post]
    User[User] --> Role[Role]
    User[User] --> UserProfile[UserProfile]
    Post[Post] --> User[User]
    Post[Post] --> Comment[Comment]
    Post[Post] --> Tag[Tag]
    Post[Post] --> Category[Category]
    Comment[Comment] --> Post[Post]
    Comment[Comment] --> User[User]
    Comment[Comment] --> Comment[Comment]
    Category[Category] --> Post[Post]
    Category[Category] --> Category[Category]
    Tag[Tag] --> Post[Post]
    Role[Role] --> User[User]
    UserProfile[UserProfile] --> User[User]